BOT_TOKEN = "8258014137:AAHJf4gXJEJ8sJsg-CClWVuifB-PqsdFv4A"

# Replace with your Telegram numeric user IDs.
ADMIN_IDS = {8374454975}

API_KEY = "MASP6HHKCNF"
API_BASE_URL = "https://api.2oo9.cloud/MXS47FLFX0U/tnevs/@public/api"

DATABASE_NAME = "otp_marketplace.db"

OTP_CHECK_INTERVAL = 5
DEFAULT_ORDER_TIMEOUT_MINUTES = 10
MAX_ACTIVE_ORDERS_PER_USER = 3
OTP_REWARD_BDT = 0.25
MIN_WITHDRAW_BDT = 50.0
WITHDRAW_NETWORK_LABEL = "SOL USDT"

HTTP_TIMEOUT_SECONDS = 15
LIVEACCESS_CACHE_SECONDS = 55
